version: '3'

services:
  whatsapp-bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: unofficial-gpt3-whatsapp-bot_whatsapp-bot:latest
    ports:
      - 8385:8385
    volumes:
      - ./store.db:/store.db
      - .env:/.env
      - ./doc.md:/doc.md
      - ./private_key.pem:/private_key.pem
